FROM node:24-bookworm-slim

WORKDIR /app

COPY package*.json ./
COPY pnpm-lock.yaml ./
COPY pnpm-workspace.yaml ./

RUN sh -c "npm i -g pnpm@10"

RUN sh -c "pnpm install"

COPY . .

RUN sh -c "pnpm build"

RUN apt-get update && apt-get install -y --no-install-recommends curl && rm -rf /var/lib/apt/lists/*

# Start the application
CMD ["pnpm", "start:prod"]
