
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const Cycle_T = {
  daily: 'daily',
  weekly: 'weekly',
  fortnightly: 'fortnightly',
  monthly: 'monthly',
  quarterly: 'quarterly',
  biannual: 'biannual',
  yearly: 'yearly',
  custom: 'custom'
} as const

export type Cycle_T = (typeof Cycle_T)[keyof typeof Cycle_T]


export const Transaction_T = {
  income: 'income',
  expense: 'expense'
} as const

export type Transaction_T = (typeof Transaction_T)[keyof typeof Transaction_T]
