
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Periodic` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Periodic
 * 
 */
export type PeriodicModel = runtime.Types.Result.DefaultSelection<Prisma.$PeriodicPayload>

export type AggregatePeriodic = {
  _count: PeriodicCountAggregateOutputType | null
  _avg: PeriodicAvgAggregateOutputType | null
  _sum: PeriodicSumAggregateOutputType | null
  _min: PeriodicMinAggregateOutputType | null
  _max: PeriodicMaxAggregateOutputType | null
}

export type PeriodicAvgAggregateOutputType = {
  duration: number | null
}

export type PeriodicSumAggregateOutputType = {
  duration: number | null
}

export type PeriodicMinAggregateOutputType = {
  id: string | null
  transactionId: string | null
  cycle: $Enums.Cycle_T | null
  duration: number | null
  nextOcurrence: Date | null
  createdAt: Date | null
  updateAt: Date | null
}

export type PeriodicMaxAggregateOutputType = {
  id: string | null
  transactionId: string | null
  cycle: $Enums.Cycle_T | null
  duration: number | null
  nextOcurrence: Date | null
  createdAt: Date | null
  updateAt: Date | null
}

export type PeriodicCountAggregateOutputType = {
  id: number
  transactionId: number
  cycle: number
  duration: number
  nextOcurrence: number
  createdAt: number
  updateAt: number
  _all: number
}


export type PeriodicAvgAggregateInputType = {
  duration?: true
}

export type PeriodicSumAggregateInputType = {
  duration?: true
}

export type PeriodicMinAggregateInputType = {
  id?: true
  transactionId?: true
  cycle?: true
  duration?: true
  nextOcurrence?: true
  createdAt?: true
  updateAt?: true
}

export type PeriodicMaxAggregateInputType = {
  id?: true
  transactionId?: true
  cycle?: true
  duration?: true
  nextOcurrence?: true
  createdAt?: true
  updateAt?: true
}

export type PeriodicCountAggregateInputType = {
  id?: true
  transactionId?: true
  cycle?: true
  duration?: true
  nextOcurrence?: true
  createdAt?: true
  updateAt?: true
  _all?: true
}

export type PeriodicAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Periodic to aggregate.
   */
  where?: Prisma.PeriodicWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Periodics to fetch.
   */
  orderBy?: Prisma.PeriodicOrderByWithRelationInput | Prisma.PeriodicOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PeriodicWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Periodics from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Periodics.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Periodics
  **/
  _count?: true | PeriodicCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PeriodicAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PeriodicSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PeriodicMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PeriodicMaxAggregateInputType
}

export type GetPeriodicAggregateType<T extends PeriodicAggregateArgs> = {
      [P in keyof T & keyof AggregatePeriodic]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePeriodic[P]>
    : Prisma.GetScalarType<T[P], AggregatePeriodic[P]>
}




export type PeriodicGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PeriodicWhereInput
  orderBy?: Prisma.PeriodicOrderByWithAggregationInput | Prisma.PeriodicOrderByWithAggregationInput[]
  by: Prisma.PeriodicScalarFieldEnum[] | Prisma.PeriodicScalarFieldEnum
  having?: Prisma.PeriodicScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PeriodicCountAggregateInputType | true
  _avg?: PeriodicAvgAggregateInputType
  _sum?: PeriodicSumAggregateInputType
  _min?: PeriodicMinAggregateInputType
  _max?: PeriodicMaxAggregateInputType
}

export type PeriodicGroupByOutputType = {
  id: string
  transactionId: string
  cycle: $Enums.Cycle_T
  duration: number | null
  nextOcurrence: Date
  createdAt: Date
  updateAt: Date
  _count: PeriodicCountAggregateOutputType | null
  _avg: PeriodicAvgAggregateOutputType | null
  _sum: PeriodicSumAggregateOutputType | null
  _min: PeriodicMinAggregateOutputType | null
  _max: PeriodicMaxAggregateOutputType | null
}

type GetPeriodicGroupByPayload<T extends PeriodicGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PeriodicGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PeriodicGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PeriodicGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PeriodicGroupByOutputType[P]>
      }
    >
  >



export type PeriodicWhereInput = {
  AND?: Prisma.PeriodicWhereInput | Prisma.PeriodicWhereInput[]
  OR?: Prisma.PeriodicWhereInput[]
  NOT?: Prisma.PeriodicWhereInput | Prisma.PeriodicWhereInput[]
  id?: Prisma.StringFilter<"Periodic"> | string
  transactionId?: Prisma.StringFilter<"Periodic"> | string
  cycle?: Prisma.EnumCycle_TFilter<"Periodic"> | $Enums.Cycle_T
  duration?: Prisma.IntNullableFilter<"Periodic"> | number | null
  nextOcurrence?: Prisma.DateTimeFilter<"Periodic"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"Periodic"> | Date | string
  updateAt?: Prisma.DateTimeFilter<"Periodic"> | Date | string
  transaction?: Prisma.XOR<Prisma.TransactionScalarRelationFilter, Prisma.TransactionWhereInput>
}

export type PeriodicOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  transactionId?: Prisma.SortOrder
  cycle?: Prisma.SortOrder
  duration?: Prisma.SortOrderInput | Prisma.SortOrder
  nextOcurrence?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updateAt?: Prisma.SortOrder
  transaction?: Prisma.TransactionOrderByWithRelationInput
}

export type PeriodicWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  transactionId?: string
  AND?: Prisma.PeriodicWhereInput | Prisma.PeriodicWhereInput[]
  OR?: Prisma.PeriodicWhereInput[]
  NOT?: Prisma.PeriodicWhereInput | Prisma.PeriodicWhereInput[]
  cycle?: Prisma.EnumCycle_TFilter<"Periodic"> | $Enums.Cycle_T
  duration?: Prisma.IntNullableFilter<"Periodic"> | number | null
  nextOcurrence?: Prisma.DateTimeFilter<"Periodic"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"Periodic"> | Date | string
  updateAt?: Prisma.DateTimeFilter<"Periodic"> | Date | string
  transaction?: Prisma.XOR<Prisma.TransactionScalarRelationFilter, Prisma.TransactionWhereInput>
}, "id" | "transactionId">

export type PeriodicOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  transactionId?: Prisma.SortOrder
  cycle?: Prisma.SortOrder
  duration?: Prisma.SortOrderInput | Prisma.SortOrder
  nextOcurrence?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updateAt?: Prisma.SortOrder
  _count?: Prisma.PeriodicCountOrderByAggregateInput
  _avg?: Prisma.PeriodicAvgOrderByAggregateInput
  _max?: Prisma.PeriodicMaxOrderByAggregateInput
  _min?: Prisma.PeriodicMinOrderByAggregateInput
  _sum?: Prisma.PeriodicSumOrderByAggregateInput
}

export type PeriodicScalarWhereWithAggregatesInput = {
  AND?: Prisma.PeriodicScalarWhereWithAggregatesInput | Prisma.PeriodicScalarWhereWithAggregatesInput[]
  OR?: Prisma.PeriodicScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PeriodicScalarWhereWithAggregatesInput | Prisma.PeriodicScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Periodic"> | string
  transactionId?: Prisma.StringWithAggregatesFilter<"Periodic"> | string
  cycle?: Prisma.EnumCycle_TWithAggregatesFilter<"Periodic"> | $Enums.Cycle_T
  duration?: Prisma.IntNullableWithAggregatesFilter<"Periodic"> | number | null
  nextOcurrence?: Prisma.DateTimeWithAggregatesFilter<"Periodic"> | Date | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Periodic"> | Date | string
  updateAt?: Prisma.DateTimeWithAggregatesFilter<"Periodic"> | Date | string
}

export type PeriodicCreateInput = {
  id?: string
  cycle: $Enums.Cycle_T
  duration?: number | null
  nextOcurrence: Date | string
  createdAt?: Date | string
  updateAt?: Date | string
  transaction: Prisma.TransactionCreateNestedOneWithoutPeriodicsInput
}

export type PeriodicUncheckedCreateInput = {
  id?: string
  transactionId: string
  cycle: $Enums.Cycle_T
  duration?: number | null
  nextOcurrence: Date | string
  createdAt?: Date | string
  updateAt?: Date | string
}

export type PeriodicUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  cycle?: Prisma.EnumCycle_TFieldUpdateOperationsInput | $Enums.Cycle_T
  duration?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  nextOcurrence?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updateAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  transaction?: Prisma.TransactionUpdateOneRequiredWithoutPeriodicsNestedInput
}

export type PeriodicUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  transactionId?: Prisma.StringFieldUpdateOperationsInput | string
  cycle?: Prisma.EnumCycle_TFieldUpdateOperationsInput | $Enums.Cycle_T
  duration?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  nextOcurrence?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updateAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PeriodicCreateManyInput = {
  id?: string
  transactionId: string
  cycle: $Enums.Cycle_T
  duration?: number | null
  nextOcurrence: Date | string
  createdAt?: Date | string
  updateAt?: Date | string
}

export type PeriodicUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  cycle?: Prisma.EnumCycle_TFieldUpdateOperationsInput | $Enums.Cycle_T
  duration?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  nextOcurrence?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updateAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PeriodicUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  transactionId?: Prisma.StringFieldUpdateOperationsInput | string
  cycle?: Prisma.EnumCycle_TFieldUpdateOperationsInput | $Enums.Cycle_T
  duration?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  nextOcurrence?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updateAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PeriodicListRelationFilter = {
  every?: Prisma.PeriodicWhereInput
  some?: Prisma.PeriodicWhereInput
  none?: Prisma.PeriodicWhereInput
}

export type PeriodicOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type PeriodicCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  transactionId?: Prisma.SortOrder
  cycle?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  nextOcurrence?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updateAt?: Prisma.SortOrder
}

export type PeriodicAvgOrderByAggregateInput = {
  duration?: Prisma.SortOrder
}

export type PeriodicMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  transactionId?: Prisma.SortOrder
  cycle?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  nextOcurrence?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updateAt?: Prisma.SortOrder
}

export type PeriodicMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  transactionId?: Prisma.SortOrder
  cycle?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  nextOcurrence?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updateAt?: Prisma.SortOrder
}

export type PeriodicSumOrderByAggregateInput = {
  duration?: Prisma.SortOrder
}

export type PeriodicCreateNestedManyWithoutTransactionInput = {
  create?: Prisma.XOR<Prisma.PeriodicCreateWithoutTransactionInput, Prisma.PeriodicUncheckedCreateWithoutTransactionInput> | Prisma.PeriodicCreateWithoutTransactionInput[] | Prisma.PeriodicUncheckedCreateWithoutTransactionInput[]
  connectOrCreate?: Prisma.PeriodicCreateOrConnectWithoutTransactionInput | Prisma.PeriodicCreateOrConnectWithoutTransactionInput[]
  createMany?: Prisma.PeriodicCreateManyTransactionInputEnvelope
  connect?: Prisma.PeriodicWhereUniqueInput | Prisma.PeriodicWhereUniqueInput[]
}

export type PeriodicUncheckedCreateNestedManyWithoutTransactionInput = {
  create?: Prisma.XOR<Prisma.PeriodicCreateWithoutTransactionInput, Prisma.PeriodicUncheckedCreateWithoutTransactionInput> | Prisma.PeriodicCreateWithoutTransactionInput[] | Prisma.PeriodicUncheckedCreateWithoutTransactionInput[]
  connectOrCreate?: Prisma.PeriodicCreateOrConnectWithoutTransactionInput | Prisma.PeriodicCreateOrConnectWithoutTransactionInput[]
  createMany?: Prisma.PeriodicCreateManyTransactionInputEnvelope
  connect?: Prisma.PeriodicWhereUniqueInput | Prisma.PeriodicWhereUniqueInput[]
}

export type PeriodicUpdateManyWithoutTransactionNestedInput = {
  create?: Prisma.XOR<Prisma.PeriodicCreateWithoutTransactionInput, Prisma.PeriodicUncheckedCreateWithoutTransactionInput> | Prisma.PeriodicCreateWithoutTransactionInput[] | Prisma.PeriodicUncheckedCreateWithoutTransactionInput[]
  connectOrCreate?: Prisma.PeriodicCreateOrConnectWithoutTransactionInput | Prisma.PeriodicCreateOrConnectWithoutTransactionInput[]
  upsert?: Prisma.PeriodicUpsertWithWhereUniqueWithoutTransactionInput | Prisma.PeriodicUpsertWithWhereUniqueWithoutTransactionInput[]
  createMany?: Prisma.PeriodicCreateManyTransactionInputEnvelope
  set?: Prisma.PeriodicWhereUniqueInput | Prisma.PeriodicWhereUniqueInput[]
  disconnect?: Prisma.PeriodicWhereUniqueInput | Prisma.PeriodicWhereUniqueInput[]
  delete?: Prisma.PeriodicWhereUniqueInput | Prisma.PeriodicWhereUniqueInput[]
  connect?: Prisma.PeriodicWhereUniqueInput | Prisma.PeriodicWhereUniqueInput[]
  update?: Prisma.PeriodicUpdateWithWhereUniqueWithoutTransactionInput | Prisma.PeriodicUpdateWithWhereUniqueWithoutTransactionInput[]
  updateMany?: Prisma.PeriodicUpdateManyWithWhereWithoutTransactionInput | Prisma.PeriodicUpdateManyWithWhereWithoutTransactionInput[]
  deleteMany?: Prisma.PeriodicScalarWhereInput | Prisma.PeriodicScalarWhereInput[]
}

export type PeriodicUncheckedUpdateManyWithoutTransactionNestedInput = {
  create?: Prisma.XOR<Prisma.PeriodicCreateWithoutTransactionInput, Prisma.PeriodicUncheckedCreateWithoutTransactionInput> | Prisma.PeriodicCreateWithoutTransactionInput[] | Prisma.PeriodicUncheckedCreateWithoutTransactionInput[]
  connectOrCreate?: Prisma.PeriodicCreateOrConnectWithoutTransactionInput | Prisma.PeriodicCreateOrConnectWithoutTransactionInput[]
  upsert?: Prisma.PeriodicUpsertWithWhereUniqueWithoutTransactionInput | Prisma.PeriodicUpsertWithWhereUniqueWithoutTransactionInput[]
  createMany?: Prisma.PeriodicCreateManyTransactionInputEnvelope
  set?: Prisma.PeriodicWhereUniqueInput | Prisma.PeriodicWhereUniqueInput[]
  disconnect?: Prisma.PeriodicWhereUniqueInput | Prisma.PeriodicWhereUniqueInput[]
  delete?: Prisma.PeriodicWhereUniqueInput | Prisma.PeriodicWhereUniqueInput[]
  connect?: Prisma.PeriodicWhereUniqueInput | Prisma.PeriodicWhereUniqueInput[]
  update?: Prisma.PeriodicUpdateWithWhereUniqueWithoutTransactionInput | Prisma.PeriodicUpdateWithWhereUniqueWithoutTransactionInput[]
  updateMany?: Prisma.PeriodicUpdateManyWithWhereWithoutTransactionInput | Prisma.PeriodicUpdateManyWithWhereWithoutTransactionInput[]
  deleteMany?: Prisma.PeriodicScalarWhereInput | Prisma.PeriodicScalarWhereInput[]
}

export type EnumCycle_TFieldUpdateOperationsInput = {
  set?: $Enums.Cycle_T
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type PeriodicCreateWithoutTransactionInput = {
  id?: string
  cycle: $Enums.Cycle_T
  duration?: number | null
  nextOcurrence: Date | string
  createdAt?: Date | string
  updateAt?: Date | string
}

export type PeriodicUncheckedCreateWithoutTransactionInput = {
  id?: string
  cycle: $Enums.Cycle_T
  duration?: number | null
  nextOcurrence: Date | string
  createdAt?: Date | string
  updateAt?: Date | string
}

export type PeriodicCreateOrConnectWithoutTransactionInput = {
  where: Prisma.PeriodicWhereUniqueInput
  create: Prisma.XOR<Prisma.PeriodicCreateWithoutTransactionInput, Prisma.PeriodicUncheckedCreateWithoutTransactionInput>
}

export type PeriodicCreateManyTransactionInputEnvelope = {
  data: Prisma.PeriodicCreateManyTransactionInput | Prisma.PeriodicCreateManyTransactionInput[]
  skipDuplicates?: boolean
}

export type PeriodicUpsertWithWhereUniqueWithoutTransactionInput = {
  where: Prisma.PeriodicWhereUniqueInput
  update: Prisma.XOR<Prisma.PeriodicUpdateWithoutTransactionInput, Prisma.PeriodicUncheckedUpdateWithoutTransactionInput>
  create: Prisma.XOR<Prisma.PeriodicCreateWithoutTransactionInput, Prisma.PeriodicUncheckedCreateWithoutTransactionInput>
}

export type PeriodicUpdateWithWhereUniqueWithoutTransactionInput = {
  where: Prisma.PeriodicWhereUniqueInput
  data: Prisma.XOR<Prisma.PeriodicUpdateWithoutTransactionInput, Prisma.PeriodicUncheckedUpdateWithoutTransactionInput>
}

export type PeriodicUpdateManyWithWhereWithoutTransactionInput = {
  where: Prisma.PeriodicScalarWhereInput
  data: Prisma.XOR<Prisma.PeriodicUpdateManyMutationInput, Prisma.PeriodicUncheckedUpdateManyWithoutTransactionInput>
}

export type PeriodicScalarWhereInput = {
  AND?: Prisma.PeriodicScalarWhereInput | Prisma.PeriodicScalarWhereInput[]
  OR?: Prisma.PeriodicScalarWhereInput[]
  NOT?: Prisma.PeriodicScalarWhereInput | Prisma.PeriodicScalarWhereInput[]
  id?: Prisma.StringFilter<"Periodic"> | string
  transactionId?: Prisma.StringFilter<"Periodic"> | string
  cycle?: Prisma.EnumCycle_TFilter<"Periodic"> | $Enums.Cycle_T
  duration?: Prisma.IntNullableFilter<"Periodic"> | number | null
  nextOcurrence?: Prisma.DateTimeFilter<"Periodic"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"Periodic"> | Date | string
  updateAt?: Prisma.DateTimeFilter<"Periodic"> | Date | string
}

export type PeriodicCreateManyTransactionInput = {
  id?: string
  cycle: $Enums.Cycle_T
  duration?: number | null
  nextOcurrence: Date | string
  createdAt?: Date | string
  updateAt?: Date | string
}

export type PeriodicUpdateWithoutTransactionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  cycle?: Prisma.EnumCycle_TFieldUpdateOperationsInput | $Enums.Cycle_T
  duration?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  nextOcurrence?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updateAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PeriodicUncheckedUpdateWithoutTransactionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  cycle?: Prisma.EnumCycle_TFieldUpdateOperationsInput | $Enums.Cycle_T
  duration?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  nextOcurrence?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updateAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PeriodicUncheckedUpdateManyWithoutTransactionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  cycle?: Prisma.EnumCycle_TFieldUpdateOperationsInput | $Enums.Cycle_T
  duration?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  nextOcurrence?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updateAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type PeriodicSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  transactionId?: boolean
  cycle?: boolean
  duration?: boolean
  nextOcurrence?: boolean
  createdAt?: boolean
  updateAt?: boolean
  transaction?: boolean | Prisma.TransactionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["periodic"]>

export type PeriodicSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  transactionId?: boolean
  cycle?: boolean
  duration?: boolean
  nextOcurrence?: boolean
  createdAt?: boolean
  updateAt?: boolean
  transaction?: boolean | Prisma.TransactionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["periodic"]>

export type PeriodicSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  transactionId?: boolean
  cycle?: boolean
  duration?: boolean
  nextOcurrence?: boolean
  createdAt?: boolean
  updateAt?: boolean
  transaction?: boolean | Prisma.TransactionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["periodic"]>

export type PeriodicSelectScalar = {
  id?: boolean
  transactionId?: boolean
  cycle?: boolean
  duration?: boolean
  nextOcurrence?: boolean
  createdAt?: boolean
  updateAt?: boolean
}

export type PeriodicOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "transactionId" | "cycle" | "duration" | "nextOcurrence" | "createdAt" | "updateAt", ExtArgs["result"]["periodic"]>
export type PeriodicInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  transaction?: boolean | Prisma.TransactionDefaultArgs<ExtArgs>
}
export type PeriodicIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  transaction?: boolean | Prisma.TransactionDefaultArgs<ExtArgs>
}
export type PeriodicIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  transaction?: boolean | Prisma.TransactionDefaultArgs<ExtArgs>
}

export type $PeriodicPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Periodic"
  objects: {
    transaction: Prisma.$TransactionPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    transactionId: string
    cycle: $Enums.Cycle_T
    duration: number | null
    nextOcurrence: Date
    createdAt: Date
    updateAt: Date
  }, ExtArgs["result"]["periodic"]>
  composites: {}
}

export type PeriodicGetPayload<S extends boolean | null | undefined | PeriodicDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PeriodicPayload, S>

export type PeriodicCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PeriodicFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PeriodicCountAggregateInputType | true
  }

export interface PeriodicDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Periodic'], meta: { name: 'Periodic' } }
  /**
   * Find zero or one Periodic that matches the filter.
   * @param {PeriodicFindUniqueArgs} args - Arguments to find a Periodic
   * @example
   * // Get one Periodic
   * const periodic = await prisma.periodic.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PeriodicFindUniqueArgs>(args: Prisma.SelectSubset<T, PeriodicFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PeriodicClient<runtime.Types.Result.GetResult<Prisma.$PeriodicPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Periodic that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PeriodicFindUniqueOrThrowArgs} args - Arguments to find a Periodic
   * @example
   * // Get one Periodic
   * const periodic = await prisma.periodic.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PeriodicFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PeriodicFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PeriodicClient<runtime.Types.Result.GetResult<Prisma.$PeriodicPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Periodic that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PeriodicFindFirstArgs} args - Arguments to find a Periodic
   * @example
   * // Get one Periodic
   * const periodic = await prisma.periodic.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PeriodicFindFirstArgs>(args?: Prisma.SelectSubset<T, PeriodicFindFirstArgs<ExtArgs>>): Prisma.Prisma__PeriodicClient<runtime.Types.Result.GetResult<Prisma.$PeriodicPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Periodic that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PeriodicFindFirstOrThrowArgs} args - Arguments to find a Periodic
   * @example
   * // Get one Periodic
   * const periodic = await prisma.periodic.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PeriodicFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PeriodicFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PeriodicClient<runtime.Types.Result.GetResult<Prisma.$PeriodicPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Periodics that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PeriodicFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Periodics
   * const periodics = await prisma.periodic.findMany()
   * 
   * // Get first 10 Periodics
   * const periodics = await prisma.periodic.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const periodicWithIdOnly = await prisma.periodic.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PeriodicFindManyArgs>(args?: Prisma.SelectSubset<T, PeriodicFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PeriodicPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Periodic.
   * @param {PeriodicCreateArgs} args - Arguments to create a Periodic.
   * @example
   * // Create one Periodic
   * const Periodic = await prisma.periodic.create({
   *   data: {
   *     // ... data to create a Periodic
   *   }
   * })
   * 
   */
  create<T extends PeriodicCreateArgs>(args: Prisma.SelectSubset<T, PeriodicCreateArgs<ExtArgs>>): Prisma.Prisma__PeriodicClient<runtime.Types.Result.GetResult<Prisma.$PeriodicPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Periodics.
   * @param {PeriodicCreateManyArgs} args - Arguments to create many Periodics.
   * @example
   * // Create many Periodics
   * const periodic = await prisma.periodic.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PeriodicCreateManyArgs>(args?: Prisma.SelectSubset<T, PeriodicCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Periodics and returns the data saved in the database.
   * @param {PeriodicCreateManyAndReturnArgs} args - Arguments to create many Periodics.
   * @example
   * // Create many Periodics
   * const periodic = await prisma.periodic.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Periodics and only return the `id`
   * const periodicWithIdOnly = await prisma.periodic.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PeriodicCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PeriodicCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PeriodicPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Periodic.
   * @param {PeriodicDeleteArgs} args - Arguments to delete one Periodic.
   * @example
   * // Delete one Periodic
   * const Periodic = await prisma.periodic.delete({
   *   where: {
   *     // ... filter to delete one Periodic
   *   }
   * })
   * 
   */
  delete<T extends PeriodicDeleteArgs>(args: Prisma.SelectSubset<T, PeriodicDeleteArgs<ExtArgs>>): Prisma.Prisma__PeriodicClient<runtime.Types.Result.GetResult<Prisma.$PeriodicPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Periodic.
   * @param {PeriodicUpdateArgs} args - Arguments to update one Periodic.
   * @example
   * // Update one Periodic
   * const periodic = await prisma.periodic.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PeriodicUpdateArgs>(args: Prisma.SelectSubset<T, PeriodicUpdateArgs<ExtArgs>>): Prisma.Prisma__PeriodicClient<runtime.Types.Result.GetResult<Prisma.$PeriodicPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Periodics.
   * @param {PeriodicDeleteManyArgs} args - Arguments to filter Periodics to delete.
   * @example
   * // Delete a few Periodics
   * const { count } = await prisma.periodic.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PeriodicDeleteManyArgs>(args?: Prisma.SelectSubset<T, PeriodicDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Periodics.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PeriodicUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Periodics
   * const periodic = await prisma.periodic.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PeriodicUpdateManyArgs>(args: Prisma.SelectSubset<T, PeriodicUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Periodics and returns the data updated in the database.
   * @param {PeriodicUpdateManyAndReturnArgs} args - Arguments to update many Periodics.
   * @example
   * // Update many Periodics
   * const periodic = await prisma.periodic.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Periodics and only return the `id`
   * const periodicWithIdOnly = await prisma.periodic.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PeriodicUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PeriodicUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PeriodicPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Periodic.
   * @param {PeriodicUpsertArgs} args - Arguments to update or create a Periodic.
   * @example
   * // Update or create a Periodic
   * const periodic = await prisma.periodic.upsert({
   *   create: {
   *     // ... data to create a Periodic
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Periodic we want to update
   *   }
   * })
   */
  upsert<T extends PeriodicUpsertArgs>(args: Prisma.SelectSubset<T, PeriodicUpsertArgs<ExtArgs>>): Prisma.Prisma__PeriodicClient<runtime.Types.Result.GetResult<Prisma.$PeriodicPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Periodics.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PeriodicCountArgs} args - Arguments to filter Periodics to count.
   * @example
   * // Count the number of Periodics
   * const count = await prisma.periodic.count({
   *   where: {
   *     // ... the filter for the Periodics we want to count
   *   }
   * })
  **/
  count<T extends PeriodicCountArgs>(
    args?: Prisma.Subset<T, PeriodicCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PeriodicCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Periodic.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PeriodicAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PeriodicAggregateArgs>(args: Prisma.Subset<T, PeriodicAggregateArgs>): Prisma.PrismaPromise<GetPeriodicAggregateType<T>>

  /**
   * Group by Periodic.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PeriodicGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PeriodicGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PeriodicGroupByArgs['orderBy'] }
      : { orderBy?: PeriodicGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PeriodicGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPeriodicGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Periodic model
 */
readonly fields: PeriodicFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Periodic.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PeriodicClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  transaction<T extends Prisma.TransactionDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TransactionDefaultArgs<ExtArgs>>): Prisma.Prisma__TransactionClient<runtime.Types.Result.GetResult<Prisma.$TransactionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Periodic model
 */
export interface PeriodicFieldRefs {
  readonly id: Prisma.FieldRef<"Periodic", 'String'>
  readonly transactionId: Prisma.FieldRef<"Periodic", 'String'>
  readonly cycle: Prisma.FieldRef<"Periodic", 'Cycle_T'>
  readonly duration: Prisma.FieldRef<"Periodic", 'Int'>
  readonly nextOcurrence: Prisma.FieldRef<"Periodic", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"Periodic", 'DateTime'>
  readonly updateAt: Prisma.FieldRef<"Periodic", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Periodic findUnique
 */
export type PeriodicFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Periodic
   */
  select?: Prisma.PeriodicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Periodic
   */
  omit?: Prisma.PeriodicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PeriodicInclude<ExtArgs> | null
  /**
   * Filter, which Periodic to fetch.
   */
  where: Prisma.PeriodicWhereUniqueInput
}

/**
 * Periodic findUniqueOrThrow
 */
export type PeriodicFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Periodic
   */
  select?: Prisma.PeriodicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Periodic
   */
  omit?: Prisma.PeriodicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PeriodicInclude<ExtArgs> | null
  /**
   * Filter, which Periodic to fetch.
   */
  where: Prisma.PeriodicWhereUniqueInput
}

/**
 * Periodic findFirst
 */
export type PeriodicFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Periodic
   */
  select?: Prisma.PeriodicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Periodic
   */
  omit?: Prisma.PeriodicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PeriodicInclude<ExtArgs> | null
  /**
   * Filter, which Periodic to fetch.
   */
  where?: Prisma.PeriodicWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Periodics to fetch.
   */
  orderBy?: Prisma.PeriodicOrderByWithRelationInput | Prisma.PeriodicOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Periodics.
   */
  cursor?: Prisma.PeriodicWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Periodics from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Periodics.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Periodics.
   */
  distinct?: Prisma.PeriodicScalarFieldEnum | Prisma.PeriodicScalarFieldEnum[]
}

/**
 * Periodic findFirstOrThrow
 */
export type PeriodicFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Periodic
   */
  select?: Prisma.PeriodicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Periodic
   */
  omit?: Prisma.PeriodicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PeriodicInclude<ExtArgs> | null
  /**
   * Filter, which Periodic to fetch.
   */
  where?: Prisma.PeriodicWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Periodics to fetch.
   */
  orderBy?: Prisma.PeriodicOrderByWithRelationInput | Prisma.PeriodicOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Periodics.
   */
  cursor?: Prisma.PeriodicWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Periodics from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Periodics.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Periodics.
   */
  distinct?: Prisma.PeriodicScalarFieldEnum | Prisma.PeriodicScalarFieldEnum[]
}

/**
 * Periodic findMany
 */
export type PeriodicFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Periodic
   */
  select?: Prisma.PeriodicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Periodic
   */
  omit?: Prisma.PeriodicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PeriodicInclude<ExtArgs> | null
  /**
   * Filter, which Periodics to fetch.
   */
  where?: Prisma.PeriodicWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Periodics to fetch.
   */
  orderBy?: Prisma.PeriodicOrderByWithRelationInput | Prisma.PeriodicOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Periodics.
   */
  cursor?: Prisma.PeriodicWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Periodics from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Periodics.
   */
  skip?: number
  distinct?: Prisma.PeriodicScalarFieldEnum | Prisma.PeriodicScalarFieldEnum[]
}

/**
 * Periodic create
 */
export type PeriodicCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Periodic
   */
  select?: Prisma.PeriodicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Periodic
   */
  omit?: Prisma.PeriodicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PeriodicInclude<ExtArgs> | null
  /**
   * The data needed to create a Periodic.
   */
  data: Prisma.XOR<Prisma.PeriodicCreateInput, Prisma.PeriodicUncheckedCreateInput>
}

/**
 * Periodic createMany
 */
export type PeriodicCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Periodics.
   */
  data: Prisma.PeriodicCreateManyInput | Prisma.PeriodicCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Periodic createManyAndReturn
 */
export type PeriodicCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Periodic
   */
  select?: Prisma.PeriodicSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Periodic
   */
  omit?: Prisma.PeriodicOmit<ExtArgs> | null
  /**
   * The data used to create many Periodics.
   */
  data: Prisma.PeriodicCreateManyInput | Prisma.PeriodicCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PeriodicIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Periodic update
 */
export type PeriodicUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Periodic
   */
  select?: Prisma.PeriodicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Periodic
   */
  omit?: Prisma.PeriodicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PeriodicInclude<ExtArgs> | null
  /**
   * The data needed to update a Periodic.
   */
  data: Prisma.XOR<Prisma.PeriodicUpdateInput, Prisma.PeriodicUncheckedUpdateInput>
  /**
   * Choose, which Periodic to update.
   */
  where: Prisma.PeriodicWhereUniqueInput
}

/**
 * Periodic updateMany
 */
export type PeriodicUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Periodics.
   */
  data: Prisma.XOR<Prisma.PeriodicUpdateManyMutationInput, Prisma.PeriodicUncheckedUpdateManyInput>
  /**
   * Filter which Periodics to update
   */
  where?: Prisma.PeriodicWhereInput
  /**
   * Limit how many Periodics to update.
   */
  limit?: number
}

/**
 * Periodic updateManyAndReturn
 */
export type PeriodicUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Periodic
   */
  select?: Prisma.PeriodicSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Periodic
   */
  omit?: Prisma.PeriodicOmit<ExtArgs> | null
  /**
   * The data used to update Periodics.
   */
  data: Prisma.XOR<Prisma.PeriodicUpdateManyMutationInput, Prisma.PeriodicUncheckedUpdateManyInput>
  /**
   * Filter which Periodics to update
   */
  where?: Prisma.PeriodicWhereInput
  /**
   * Limit how many Periodics to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PeriodicIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Periodic upsert
 */
export type PeriodicUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Periodic
   */
  select?: Prisma.PeriodicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Periodic
   */
  omit?: Prisma.PeriodicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PeriodicInclude<ExtArgs> | null
  /**
   * The filter to search for the Periodic to update in case it exists.
   */
  where: Prisma.PeriodicWhereUniqueInput
  /**
   * In case the Periodic found by the `where` argument doesn't exist, create a new Periodic with this data.
   */
  create: Prisma.XOR<Prisma.PeriodicCreateInput, Prisma.PeriodicUncheckedCreateInput>
  /**
   * In case the Periodic was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PeriodicUpdateInput, Prisma.PeriodicUncheckedUpdateInput>
}

/**
 * Periodic delete
 */
export type PeriodicDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Periodic
   */
  select?: Prisma.PeriodicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Periodic
   */
  omit?: Prisma.PeriodicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PeriodicInclude<ExtArgs> | null
  /**
   * Filter which Periodic to delete.
   */
  where: Prisma.PeriodicWhereUniqueInput
}

/**
 * Periodic deleteMany
 */
export type PeriodicDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Periodics to delete
   */
  where?: Prisma.PeriodicWhereInput
  /**
   * Limit how many Periodics to delete.
   */
  limit?: number
}

/**
 * Periodic without action
 */
export type PeriodicDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Periodic
   */
  select?: Prisma.PeriodicSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Periodic
   */
  omit?: Prisma.PeriodicOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PeriodicInclude<ExtArgs> | null
}
