
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TagsOnTransactions` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model TagsOnTransactions
 * 
 */
export type TagsOnTransactionsModel = runtime.Types.Result.DefaultSelection<Prisma.$TagsOnTransactionsPayload>

export type AggregateTagsOnTransactions = {
  _count: TagsOnTransactionsCountAggregateOutputType | null
  _min: TagsOnTransactionsMinAggregateOutputType | null
  _max: TagsOnTransactionsMaxAggregateOutputType | null
}

export type TagsOnTransactionsMinAggregateOutputType = {
  tagId: string | null
  transactionId: string | null
}

export type TagsOnTransactionsMaxAggregateOutputType = {
  tagId: string | null
  transactionId: string | null
}

export type TagsOnTransactionsCountAggregateOutputType = {
  tagId: number
  transactionId: number
  _all: number
}


export type TagsOnTransactionsMinAggregateInputType = {
  tagId?: true
  transactionId?: true
}

export type TagsOnTransactionsMaxAggregateInputType = {
  tagId?: true
  transactionId?: true
}

export type TagsOnTransactionsCountAggregateInputType = {
  tagId?: true
  transactionId?: true
  _all?: true
}

export type TagsOnTransactionsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TagsOnTransactions to aggregate.
   */
  where?: Prisma.TagsOnTransactionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TagsOnTransactions to fetch.
   */
  orderBy?: Prisma.TagsOnTransactionsOrderByWithRelationInput | Prisma.TagsOnTransactionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TagsOnTransactionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TagsOnTransactions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TagsOnTransactions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TagsOnTransactions
  **/
  _count?: true | TagsOnTransactionsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TagsOnTransactionsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TagsOnTransactionsMaxAggregateInputType
}

export type GetTagsOnTransactionsAggregateType<T extends TagsOnTransactionsAggregateArgs> = {
      [P in keyof T & keyof AggregateTagsOnTransactions]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTagsOnTransactions[P]>
    : Prisma.GetScalarType<T[P], AggregateTagsOnTransactions[P]>
}




export type TagsOnTransactionsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TagsOnTransactionsWhereInput
  orderBy?: Prisma.TagsOnTransactionsOrderByWithAggregationInput | Prisma.TagsOnTransactionsOrderByWithAggregationInput[]
  by: Prisma.TagsOnTransactionsScalarFieldEnum[] | Prisma.TagsOnTransactionsScalarFieldEnum
  having?: Prisma.TagsOnTransactionsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TagsOnTransactionsCountAggregateInputType | true
  _min?: TagsOnTransactionsMinAggregateInputType
  _max?: TagsOnTransactionsMaxAggregateInputType
}

export type TagsOnTransactionsGroupByOutputType = {
  tagId: string
  transactionId: string
  _count: TagsOnTransactionsCountAggregateOutputType | null
  _min: TagsOnTransactionsMinAggregateOutputType | null
  _max: TagsOnTransactionsMaxAggregateOutputType | null
}

export type GetTagsOnTransactionsGroupByPayload<T extends TagsOnTransactionsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TagsOnTransactionsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TagsOnTransactionsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TagsOnTransactionsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TagsOnTransactionsGroupByOutputType[P]>
      }
    >
  >



export type TagsOnTransactionsWhereInput = {
  AND?: Prisma.TagsOnTransactionsWhereInput | Prisma.TagsOnTransactionsWhereInput[]
  OR?: Prisma.TagsOnTransactionsWhereInput[]
  NOT?: Prisma.TagsOnTransactionsWhereInput | Prisma.TagsOnTransactionsWhereInput[]
  tagId?: Prisma.StringFilter<"TagsOnTransactions"> | string
  transactionId?: Prisma.StringFilter<"TagsOnTransactions"> | string
  tag?: Prisma.XOR<Prisma.TagsScalarRelationFilter, Prisma.TagsWhereInput>
  transaction?: Prisma.XOR<Prisma.TransactionScalarRelationFilter, Prisma.TransactionWhereInput>
}

export type TagsOnTransactionsOrderByWithRelationInput = {
  tagId?: Prisma.SortOrder
  transactionId?: Prisma.SortOrder
  tag?: Prisma.TagsOrderByWithRelationInput
  transaction?: Prisma.TransactionOrderByWithRelationInput
}

export type TagsOnTransactionsWhereUniqueInput = Prisma.AtLeast<{
  tagId_transactionId?: Prisma.TagsOnTransactionsTagIdTransactionIdCompoundUniqueInput
  AND?: Prisma.TagsOnTransactionsWhereInput | Prisma.TagsOnTransactionsWhereInput[]
  OR?: Prisma.TagsOnTransactionsWhereInput[]
  NOT?: Prisma.TagsOnTransactionsWhereInput | Prisma.TagsOnTransactionsWhereInput[]
  tagId?: Prisma.StringFilter<"TagsOnTransactions"> | string
  transactionId?: Prisma.StringFilter<"TagsOnTransactions"> | string
  tag?: Prisma.XOR<Prisma.TagsScalarRelationFilter, Prisma.TagsWhereInput>
  transaction?: Prisma.XOR<Prisma.TransactionScalarRelationFilter, Prisma.TransactionWhereInput>
}, "tagId_transactionId">

export type TagsOnTransactionsOrderByWithAggregationInput = {
  tagId?: Prisma.SortOrder
  transactionId?: Prisma.SortOrder
  _count?: Prisma.TagsOnTransactionsCountOrderByAggregateInput
  _max?: Prisma.TagsOnTransactionsMaxOrderByAggregateInput
  _min?: Prisma.TagsOnTransactionsMinOrderByAggregateInput
}

export type TagsOnTransactionsScalarWhereWithAggregatesInput = {
  AND?: Prisma.TagsOnTransactionsScalarWhereWithAggregatesInput | Prisma.TagsOnTransactionsScalarWhereWithAggregatesInput[]
  OR?: Prisma.TagsOnTransactionsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TagsOnTransactionsScalarWhereWithAggregatesInput | Prisma.TagsOnTransactionsScalarWhereWithAggregatesInput[]
  tagId?: Prisma.StringWithAggregatesFilter<"TagsOnTransactions"> | string
  transactionId?: Prisma.StringWithAggregatesFilter<"TagsOnTransactions"> | string
}

export type TagsOnTransactionsCreateInput = {
  tag: Prisma.TagsCreateNestedOneWithoutTagsOnTransactionsInput
  transaction: Prisma.TransactionCreateNestedOneWithoutTagsOnTransactionsInput
}

export type TagsOnTransactionsUncheckedCreateInput = {
  tagId: string
  transactionId: string
}

export type TagsOnTransactionsUpdateInput = {
  tag?: Prisma.TagsUpdateOneRequiredWithoutTagsOnTransactionsNestedInput
  transaction?: Prisma.TransactionUpdateOneRequiredWithoutTagsOnTransactionsNestedInput
}

export type TagsOnTransactionsUncheckedUpdateInput = {
  tagId?: Prisma.StringFieldUpdateOperationsInput | string
  transactionId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TagsOnTransactionsCreateManyInput = {
  tagId: string
  transactionId: string
}

export type TagsOnTransactionsUpdateManyMutationInput = {

}

export type TagsOnTransactionsUncheckedUpdateManyInput = {
  tagId?: Prisma.StringFieldUpdateOperationsInput | string
  transactionId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TagsOnTransactionsListRelationFilter = {
  every?: Prisma.TagsOnTransactionsWhereInput
  some?: Prisma.TagsOnTransactionsWhereInput
  none?: Prisma.TagsOnTransactionsWhereInput
}

export type TagsOnTransactionsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TagsOnTransactionsTagIdTransactionIdCompoundUniqueInput = {
  tagId: string
  transactionId: string
}

export type TagsOnTransactionsCountOrderByAggregateInput = {
  tagId?: Prisma.SortOrder
  transactionId?: Prisma.SortOrder
}

export type TagsOnTransactionsMaxOrderByAggregateInput = {
  tagId?: Prisma.SortOrder
  transactionId?: Prisma.SortOrder
}

export type TagsOnTransactionsMinOrderByAggregateInput = {
  tagId?: Prisma.SortOrder
  transactionId?: Prisma.SortOrder
}

export type TagsOnTransactionsCreateNestedManyWithoutTransactionInput = {
  create?: Prisma.XOR<Prisma.TagsOnTransactionsCreateWithoutTransactionInput, Prisma.TagsOnTransactionsUncheckedCreateWithoutTransactionInput> | Prisma.TagsOnTransactionsCreateWithoutTransactionInput[] | Prisma.TagsOnTransactionsUncheckedCreateWithoutTransactionInput[]
  connectOrCreate?: Prisma.TagsOnTransactionsCreateOrConnectWithoutTransactionInput | Prisma.TagsOnTransactionsCreateOrConnectWithoutTransactionInput[]
  createMany?: Prisma.TagsOnTransactionsCreateManyTransactionInputEnvelope
  connect?: Prisma.TagsOnTransactionsWhereUniqueInput | Prisma.TagsOnTransactionsWhereUniqueInput[]
}

export type TagsOnTransactionsUncheckedCreateNestedManyWithoutTransactionInput = {
  create?: Prisma.XOR<Prisma.TagsOnTransactionsCreateWithoutTransactionInput, Prisma.TagsOnTransactionsUncheckedCreateWithoutTransactionInput> | Prisma.TagsOnTransactionsCreateWithoutTransactionInput[] | Prisma.TagsOnTransactionsUncheckedCreateWithoutTransactionInput[]
  connectOrCreate?: Prisma.TagsOnTransactionsCreateOrConnectWithoutTransactionInput | Prisma.TagsOnTransactionsCreateOrConnectWithoutTransactionInput[]
  createMany?: Prisma.TagsOnTransactionsCreateManyTransactionInputEnvelope
  connect?: Prisma.TagsOnTransactionsWhereUniqueInput | Prisma.TagsOnTransactionsWhereUniqueInput[]
}

export type TagsOnTransactionsUpdateManyWithoutTransactionNestedInput = {
  create?: Prisma.XOR<Prisma.TagsOnTransactionsCreateWithoutTransactionInput, Prisma.TagsOnTransactionsUncheckedCreateWithoutTransactionInput> | Prisma.TagsOnTransactionsCreateWithoutTransactionInput[] | Prisma.TagsOnTransactionsUncheckedCreateWithoutTransactionInput[]
  connectOrCreate?: Prisma.TagsOnTransactionsCreateOrConnectWithoutTransactionInput | Prisma.TagsOnTransactionsCreateOrConnectWithoutTransactionInput[]
  upsert?: Prisma.TagsOnTransactionsUpsertWithWhereUniqueWithoutTransactionInput | Prisma.TagsOnTransactionsUpsertWithWhereUniqueWithoutTransactionInput[]
  createMany?: Prisma.TagsOnTransactionsCreateManyTransactionInputEnvelope
  set?: Prisma.TagsOnTransactionsWhereUniqueInput | Prisma.TagsOnTransactionsWhereUniqueInput[]
  disconnect?: Prisma.TagsOnTransactionsWhereUniqueInput | Prisma.TagsOnTransactionsWhereUniqueInput[]
  delete?: Prisma.TagsOnTransactionsWhereUniqueInput | Prisma.TagsOnTransactionsWhereUniqueInput[]
  connect?: Prisma.TagsOnTransactionsWhereUniqueInput | Prisma.TagsOnTransactionsWhereUniqueInput[]
  update?: Prisma.TagsOnTransactionsUpdateWithWhereUniqueWithoutTransactionInput | Prisma.TagsOnTransactionsUpdateWithWhereUniqueWithoutTransactionInput[]
  updateMany?: Prisma.TagsOnTransactionsUpdateManyWithWhereWithoutTransactionInput | Prisma.TagsOnTransactionsUpdateManyWithWhereWithoutTransactionInput[]
  deleteMany?: Prisma.TagsOnTransactionsScalarWhereInput | Prisma.TagsOnTransactionsScalarWhereInput[]
}

export type TagsOnTransactionsUncheckedUpdateManyWithoutTransactionNestedInput = {
  create?: Prisma.XOR<Prisma.TagsOnTransactionsCreateWithoutTransactionInput, Prisma.TagsOnTransactionsUncheckedCreateWithoutTransactionInput> | Prisma.TagsOnTransactionsCreateWithoutTransactionInput[] | Prisma.TagsOnTransactionsUncheckedCreateWithoutTransactionInput[]
  connectOrCreate?: Prisma.TagsOnTransactionsCreateOrConnectWithoutTransactionInput | Prisma.TagsOnTransactionsCreateOrConnectWithoutTransactionInput[]
  upsert?: Prisma.TagsOnTransactionsUpsertWithWhereUniqueWithoutTransactionInput | Prisma.TagsOnTransactionsUpsertWithWhereUniqueWithoutTransactionInput[]
  createMany?: Prisma.TagsOnTransactionsCreateManyTransactionInputEnvelope
  set?: Prisma.TagsOnTransactionsWhereUniqueInput | Prisma.TagsOnTransactionsWhereUniqueInput[]
  disconnect?: Prisma.TagsOnTransactionsWhereUniqueInput | Prisma.TagsOnTransactionsWhereUniqueInput[]
  delete?: Prisma.TagsOnTransactionsWhereUniqueInput | Prisma.TagsOnTransactionsWhereUniqueInput[]
  connect?: Prisma.TagsOnTransactionsWhereUniqueInput | Prisma.TagsOnTransactionsWhereUniqueInput[]
  update?: Prisma.TagsOnTransactionsUpdateWithWhereUniqueWithoutTransactionInput | Prisma.TagsOnTransactionsUpdateWithWhereUniqueWithoutTransactionInput[]
  updateMany?: Prisma.TagsOnTransactionsUpdateManyWithWhereWithoutTransactionInput | Prisma.TagsOnTransactionsUpdateManyWithWhereWithoutTransactionInput[]
  deleteMany?: Prisma.TagsOnTransactionsScalarWhereInput | Prisma.TagsOnTransactionsScalarWhereInput[]
}

export type TagsOnTransactionsCreateNestedManyWithoutTagInput = {
  create?: Prisma.XOR<Prisma.TagsOnTransactionsCreateWithoutTagInput, Prisma.TagsOnTransactionsUncheckedCreateWithoutTagInput> | Prisma.TagsOnTransactionsCreateWithoutTagInput[] | Prisma.TagsOnTransactionsUncheckedCreateWithoutTagInput[]
  connectOrCreate?: Prisma.TagsOnTransactionsCreateOrConnectWithoutTagInput | Prisma.TagsOnTransactionsCreateOrConnectWithoutTagInput[]
  createMany?: Prisma.TagsOnTransactionsCreateManyTagInputEnvelope
  connect?: Prisma.TagsOnTransactionsWhereUniqueInput | Prisma.TagsOnTransactionsWhereUniqueInput[]
}

export type TagsOnTransactionsUncheckedCreateNestedManyWithoutTagInput = {
  create?: Prisma.XOR<Prisma.TagsOnTransactionsCreateWithoutTagInput, Prisma.TagsOnTransactionsUncheckedCreateWithoutTagInput> | Prisma.TagsOnTransactionsCreateWithoutTagInput[] | Prisma.TagsOnTransactionsUncheckedCreateWithoutTagInput[]
  connectOrCreate?: Prisma.TagsOnTransactionsCreateOrConnectWithoutTagInput | Prisma.TagsOnTransactionsCreateOrConnectWithoutTagInput[]
  createMany?: Prisma.TagsOnTransactionsCreateManyTagInputEnvelope
  connect?: Prisma.TagsOnTransactionsWhereUniqueInput | Prisma.TagsOnTransactionsWhereUniqueInput[]
}

export type TagsOnTransactionsUpdateManyWithoutTagNestedInput = {
  create?: Prisma.XOR<Prisma.TagsOnTransactionsCreateWithoutTagInput, Prisma.TagsOnTransactionsUncheckedCreateWithoutTagInput> | Prisma.TagsOnTransactionsCreateWithoutTagInput[] | Prisma.TagsOnTransactionsUncheckedCreateWithoutTagInput[]
  connectOrCreate?: Prisma.TagsOnTransactionsCreateOrConnectWithoutTagInput | Prisma.TagsOnTransactionsCreateOrConnectWithoutTagInput[]
  upsert?: Prisma.TagsOnTransactionsUpsertWithWhereUniqueWithoutTagInput | Prisma.TagsOnTransactionsUpsertWithWhereUniqueWithoutTagInput[]
  createMany?: Prisma.TagsOnTransactionsCreateManyTagInputEnvelope
  set?: Prisma.TagsOnTransactionsWhereUniqueInput | Prisma.TagsOnTransactionsWhereUniqueInput[]
  disconnect?: Prisma.TagsOnTransactionsWhereUniqueInput | Prisma.TagsOnTransactionsWhereUniqueInput[]
  delete?: Prisma.TagsOnTransactionsWhereUniqueInput | Prisma.TagsOnTransactionsWhereUniqueInput[]
  connect?: Prisma.TagsOnTransactionsWhereUniqueInput | Prisma.TagsOnTransactionsWhereUniqueInput[]
  update?: Prisma.TagsOnTransactionsUpdateWithWhereUniqueWithoutTagInput | Prisma.TagsOnTransactionsUpdateWithWhereUniqueWithoutTagInput[]
  updateMany?: Prisma.TagsOnTransactionsUpdateManyWithWhereWithoutTagInput | Prisma.TagsOnTransactionsUpdateManyWithWhereWithoutTagInput[]
  deleteMany?: Prisma.TagsOnTransactionsScalarWhereInput | Prisma.TagsOnTransactionsScalarWhereInput[]
}

export type TagsOnTransactionsUncheckedUpdateManyWithoutTagNestedInput = {
  create?: Prisma.XOR<Prisma.TagsOnTransactionsCreateWithoutTagInput, Prisma.TagsOnTransactionsUncheckedCreateWithoutTagInput> | Prisma.TagsOnTransactionsCreateWithoutTagInput[] | Prisma.TagsOnTransactionsUncheckedCreateWithoutTagInput[]
  connectOrCreate?: Prisma.TagsOnTransactionsCreateOrConnectWithoutTagInput | Prisma.TagsOnTransactionsCreateOrConnectWithoutTagInput[]
  upsert?: Prisma.TagsOnTransactionsUpsertWithWhereUniqueWithoutTagInput | Prisma.TagsOnTransactionsUpsertWithWhereUniqueWithoutTagInput[]
  createMany?: Prisma.TagsOnTransactionsCreateManyTagInputEnvelope
  set?: Prisma.TagsOnTransactionsWhereUniqueInput | Prisma.TagsOnTransactionsWhereUniqueInput[]
  disconnect?: Prisma.TagsOnTransactionsWhereUniqueInput | Prisma.TagsOnTransactionsWhereUniqueInput[]
  delete?: Prisma.TagsOnTransactionsWhereUniqueInput | Prisma.TagsOnTransactionsWhereUniqueInput[]
  connect?: Prisma.TagsOnTransactionsWhereUniqueInput | Prisma.TagsOnTransactionsWhereUniqueInput[]
  update?: Prisma.TagsOnTransactionsUpdateWithWhereUniqueWithoutTagInput | Prisma.TagsOnTransactionsUpdateWithWhereUniqueWithoutTagInput[]
  updateMany?: Prisma.TagsOnTransactionsUpdateManyWithWhereWithoutTagInput | Prisma.TagsOnTransactionsUpdateManyWithWhereWithoutTagInput[]
  deleteMany?: Prisma.TagsOnTransactionsScalarWhereInput | Prisma.TagsOnTransactionsScalarWhereInput[]
}

export type TagsOnTransactionsCreateWithoutTransactionInput = {
  tag: Prisma.TagsCreateNestedOneWithoutTagsOnTransactionsInput
}

export type TagsOnTransactionsUncheckedCreateWithoutTransactionInput = {
  tagId: string
}

export type TagsOnTransactionsCreateOrConnectWithoutTransactionInput = {
  where: Prisma.TagsOnTransactionsWhereUniqueInput
  create: Prisma.XOR<Prisma.TagsOnTransactionsCreateWithoutTransactionInput, Prisma.TagsOnTransactionsUncheckedCreateWithoutTransactionInput>
}

export type TagsOnTransactionsCreateManyTransactionInputEnvelope = {
  data: Prisma.TagsOnTransactionsCreateManyTransactionInput | Prisma.TagsOnTransactionsCreateManyTransactionInput[]
  skipDuplicates?: boolean
}

export type TagsOnTransactionsUpsertWithWhereUniqueWithoutTransactionInput = {
  where: Prisma.TagsOnTransactionsWhereUniqueInput
  update: Prisma.XOR<Prisma.TagsOnTransactionsUpdateWithoutTransactionInput, Prisma.TagsOnTransactionsUncheckedUpdateWithoutTransactionInput>
  create: Prisma.XOR<Prisma.TagsOnTransactionsCreateWithoutTransactionInput, Prisma.TagsOnTransactionsUncheckedCreateWithoutTransactionInput>
}

export type TagsOnTransactionsUpdateWithWhereUniqueWithoutTransactionInput = {
  where: Prisma.TagsOnTransactionsWhereUniqueInput
  data: Prisma.XOR<Prisma.TagsOnTransactionsUpdateWithoutTransactionInput, Prisma.TagsOnTransactionsUncheckedUpdateWithoutTransactionInput>
}

export type TagsOnTransactionsUpdateManyWithWhereWithoutTransactionInput = {
  where: Prisma.TagsOnTransactionsScalarWhereInput
  data: Prisma.XOR<Prisma.TagsOnTransactionsUpdateManyMutationInput, Prisma.TagsOnTransactionsUncheckedUpdateManyWithoutTransactionInput>
}

export type TagsOnTransactionsScalarWhereInput = {
  AND?: Prisma.TagsOnTransactionsScalarWhereInput | Prisma.TagsOnTransactionsScalarWhereInput[]
  OR?: Prisma.TagsOnTransactionsScalarWhereInput[]
  NOT?: Prisma.TagsOnTransactionsScalarWhereInput | Prisma.TagsOnTransactionsScalarWhereInput[]
  tagId?: Prisma.StringFilter<"TagsOnTransactions"> | string
  transactionId?: Prisma.StringFilter<"TagsOnTransactions"> | string
}

export type TagsOnTransactionsCreateWithoutTagInput = {
  transaction: Prisma.TransactionCreateNestedOneWithoutTagsOnTransactionsInput
}

export type TagsOnTransactionsUncheckedCreateWithoutTagInput = {
  transactionId: string
}

export type TagsOnTransactionsCreateOrConnectWithoutTagInput = {
  where: Prisma.TagsOnTransactionsWhereUniqueInput
  create: Prisma.XOR<Prisma.TagsOnTransactionsCreateWithoutTagInput, Prisma.TagsOnTransactionsUncheckedCreateWithoutTagInput>
}

export type TagsOnTransactionsCreateManyTagInputEnvelope = {
  data: Prisma.TagsOnTransactionsCreateManyTagInput | Prisma.TagsOnTransactionsCreateManyTagInput[]
  skipDuplicates?: boolean
}

export type TagsOnTransactionsUpsertWithWhereUniqueWithoutTagInput = {
  where: Prisma.TagsOnTransactionsWhereUniqueInput
  update: Prisma.XOR<Prisma.TagsOnTransactionsUpdateWithoutTagInput, Prisma.TagsOnTransactionsUncheckedUpdateWithoutTagInput>
  create: Prisma.XOR<Prisma.TagsOnTransactionsCreateWithoutTagInput, Prisma.TagsOnTransactionsUncheckedCreateWithoutTagInput>
}

export type TagsOnTransactionsUpdateWithWhereUniqueWithoutTagInput = {
  where: Prisma.TagsOnTransactionsWhereUniqueInput
  data: Prisma.XOR<Prisma.TagsOnTransactionsUpdateWithoutTagInput, Prisma.TagsOnTransactionsUncheckedUpdateWithoutTagInput>
}

export type TagsOnTransactionsUpdateManyWithWhereWithoutTagInput = {
  where: Prisma.TagsOnTransactionsScalarWhereInput
  data: Prisma.XOR<Prisma.TagsOnTransactionsUpdateManyMutationInput, Prisma.TagsOnTransactionsUncheckedUpdateManyWithoutTagInput>
}

export type TagsOnTransactionsCreateManyTransactionInput = {
  tagId: string
}

export type TagsOnTransactionsUpdateWithoutTransactionInput = {
  tag?: Prisma.TagsUpdateOneRequiredWithoutTagsOnTransactionsNestedInput
}

export type TagsOnTransactionsUncheckedUpdateWithoutTransactionInput = {
  tagId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TagsOnTransactionsUncheckedUpdateManyWithoutTransactionInput = {
  tagId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TagsOnTransactionsCreateManyTagInput = {
  transactionId: string
}

export type TagsOnTransactionsUpdateWithoutTagInput = {
  transaction?: Prisma.TransactionUpdateOneRequiredWithoutTagsOnTransactionsNestedInput
}

export type TagsOnTransactionsUncheckedUpdateWithoutTagInput = {
  transactionId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TagsOnTransactionsUncheckedUpdateManyWithoutTagInput = {
  transactionId?: Prisma.StringFieldUpdateOperationsInput | string
}



export type TagsOnTransactionsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  tagId?: boolean
  transactionId?: boolean
  tag?: boolean | Prisma.TagsDefaultArgs<ExtArgs>
  transaction?: boolean | Prisma.TransactionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tagsOnTransactions"]>

export type TagsOnTransactionsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  tagId?: boolean
  transactionId?: boolean
  tag?: boolean | Prisma.TagsDefaultArgs<ExtArgs>
  transaction?: boolean | Prisma.TransactionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tagsOnTransactions"]>

export type TagsOnTransactionsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  tagId?: boolean
  transactionId?: boolean
  tag?: boolean | Prisma.TagsDefaultArgs<ExtArgs>
  transaction?: boolean | Prisma.TransactionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tagsOnTransactions"]>

export type TagsOnTransactionsSelectScalar = {
  tagId?: boolean
  transactionId?: boolean
}

export type TagsOnTransactionsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"tagId" | "transactionId", ExtArgs["result"]["tagsOnTransactions"]>
export type TagsOnTransactionsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tag?: boolean | Prisma.TagsDefaultArgs<ExtArgs>
  transaction?: boolean | Prisma.TransactionDefaultArgs<ExtArgs>
}
export type TagsOnTransactionsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tag?: boolean | Prisma.TagsDefaultArgs<ExtArgs>
  transaction?: boolean | Prisma.TransactionDefaultArgs<ExtArgs>
}
export type TagsOnTransactionsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tag?: boolean | Prisma.TagsDefaultArgs<ExtArgs>
  transaction?: boolean | Prisma.TransactionDefaultArgs<ExtArgs>
}

export type $TagsOnTransactionsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TagsOnTransactions"
  objects: {
    tag: Prisma.$TagsPayload<ExtArgs>
    transaction: Prisma.$TransactionPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    tagId: string
    transactionId: string
  }, ExtArgs["result"]["tagsOnTransactions"]>
  composites: {}
}

export type TagsOnTransactionsGetPayload<S extends boolean | null | undefined | TagsOnTransactionsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TagsOnTransactionsPayload, S>

export type TagsOnTransactionsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TagsOnTransactionsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TagsOnTransactionsCountAggregateInputType | true
  }

export interface TagsOnTransactionsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TagsOnTransactions'], meta: { name: 'TagsOnTransactions' } }
  /**
   * Find zero or one TagsOnTransactions that matches the filter.
   * @param {TagsOnTransactionsFindUniqueArgs} args - Arguments to find a TagsOnTransactions
   * @example
   * // Get one TagsOnTransactions
   * const tagsOnTransactions = await prisma.tagsOnTransactions.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TagsOnTransactionsFindUniqueArgs>(args: Prisma.SelectSubset<T, TagsOnTransactionsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TagsOnTransactionsClient<runtime.Types.Result.GetResult<Prisma.$TagsOnTransactionsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TagsOnTransactions that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TagsOnTransactionsFindUniqueOrThrowArgs} args - Arguments to find a TagsOnTransactions
   * @example
   * // Get one TagsOnTransactions
   * const tagsOnTransactions = await prisma.tagsOnTransactions.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TagsOnTransactionsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TagsOnTransactionsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TagsOnTransactionsClient<runtime.Types.Result.GetResult<Prisma.$TagsOnTransactionsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TagsOnTransactions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TagsOnTransactionsFindFirstArgs} args - Arguments to find a TagsOnTransactions
   * @example
   * // Get one TagsOnTransactions
   * const tagsOnTransactions = await prisma.tagsOnTransactions.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TagsOnTransactionsFindFirstArgs>(args?: Prisma.SelectSubset<T, TagsOnTransactionsFindFirstArgs<ExtArgs>>): Prisma.Prisma__TagsOnTransactionsClient<runtime.Types.Result.GetResult<Prisma.$TagsOnTransactionsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TagsOnTransactions that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TagsOnTransactionsFindFirstOrThrowArgs} args - Arguments to find a TagsOnTransactions
   * @example
   * // Get one TagsOnTransactions
   * const tagsOnTransactions = await prisma.tagsOnTransactions.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TagsOnTransactionsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TagsOnTransactionsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TagsOnTransactionsClient<runtime.Types.Result.GetResult<Prisma.$TagsOnTransactionsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TagsOnTransactions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TagsOnTransactionsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TagsOnTransactions
   * const tagsOnTransactions = await prisma.tagsOnTransactions.findMany()
   * 
   * // Get first 10 TagsOnTransactions
   * const tagsOnTransactions = await prisma.tagsOnTransactions.findMany({ take: 10 })
   * 
   * // Only select the `tagId`
   * const tagsOnTransactionsWithTagIdOnly = await prisma.tagsOnTransactions.findMany({ select: { tagId: true } })
   * 
   */
  findMany<T extends TagsOnTransactionsFindManyArgs>(args?: Prisma.SelectSubset<T, TagsOnTransactionsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TagsOnTransactionsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TagsOnTransactions.
   * @param {TagsOnTransactionsCreateArgs} args - Arguments to create a TagsOnTransactions.
   * @example
   * // Create one TagsOnTransactions
   * const TagsOnTransactions = await prisma.tagsOnTransactions.create({
   *   data: {
   *     // ... data to create a TagsOnTransactions
   *   }
   * })
   * 
   */
  create<T extends TagsOnTransactionsCreateArgs>(args: Prisma.SelectSubset<T, TagsOnTransactionsCreateArgs<ExtArgs>>): Prisma.Prisma__TagsOnTransactionsClient<runtime.Types.Result.GetResult<Prisma.$TagsOnTransactionsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TagsOnTransactions.
   * @param {TagsOnTransactionsCreateManyArgs} args - Arguments to create many TagsOnTransactions.
   * @example
   * // Create many TagsOnTransactions
   * const tagsOnTransactions = await prisma.tagsOnTransactions.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TagsOnTransactionsCreateManyArgs>(args?: Prisma.SelectSubset<T, TagsOnTransactionsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TagsOnTransactions and returns the data saved in the database.
   * @param {TagsOnTransactionsCreateManyAndReturnArgs} args - Arguments to create many TagsOnTransactions.
   * @example
   * // Create many TagsOnTransactions
   * const tagsOnTransactions = await prisma.tagsOnTransactions.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TagsOnTransactions and only return the `tagId`
   * const tagsOnTransactionsWithTagIdOnly = await prisma.tagsOnTransactions.createManyAndReturn({
   *   select: { tagId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TagsOnTransactionsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TagsOnTransactionsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TagsOnTransactionsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TagsOnTransactions.
   * @param {TagsOnTransactionsDeleteArgs} args - Arguments to delete one TagsOnTransactions.
   * @example
   * // Delete one TagsOnTransactions
   * const TagsOnTransactions = await prisma.tagsOnTransactions.delete({
   *   where: {
   *     // ... filter to delete one TagsOnTransactions
   *   }
   * })
   * 
   */
  delete<T extends TagsOnTransactionsDeleteArgs>(args: Prisma.SelectSubset<T, TagsOnTransactionsDeleteArgs<ExtArgs>>): Prisma.Prisma__TagsOnTransactionsClient<runtime.Types.Result.GetResult<Prisma.$TagsOnTransactionsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TagsOnTransactions.
   * @param {TagsOnTransactionsUpdateArgs} args - Arguments to update one TagsOnTransactions.
   * @example
   * // Update one TagsOnTransactions
   * const tagsOnTransactions = await prisma.tagsOnTransactions.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TagsOnTransactionsUpdateArgs>(args: Prisma.SelectSubset<T, TagsOnTransactionsUpdateArgs<ExtArgs>>): Prisma.Prisma__TagsOnTransactionsClient<runtime.Types.Result.GetResult<Prisma.$TagsOnTransactionsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TagsOnTransactions.
   * @param {TagsOnTransactionsDeleteManyArgs} args - Arguments to filter TagsOnTransactions to delete.
   * @example
   * // Delete a few TagsOnTransactions
   * const { count } = await prisma.tagsOnTransactions.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TagsOnTransactionsDeleteManyArgs>(args?: Prisma.SelectSubset<T, TagsOnTransactionsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TagsOnTransactions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TagsOnTransactionsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TagsOnTransactions
   * const tagsOnTransactions = await prisma.tagsOnTransactions.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TagsOnTransactionsUpdateManyArgs>(args: Prisma.SelectSubset<T, TagsOnTransactionsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TagsOnTransactions and returns the data updated in the database.
   * @param {TagsOnTransactionsUpdateManyAndReturnArgs} args - Arguments to update many TagsOnTransactions.
   * @example
   * // Update many TagsOnTransactions
   * const tagsOnTransactions = await prisma.tagsOnTransactions.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TagsOnTransactions and only return the `tagId`
   * const tagsOnTransactionsWithTagIdOnly = await prisma.tagsOnTransactions.updateManyAndReturn({
   *   select: { tagId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TagsOnTransactionsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TagsOnTransactionsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TagsOnTransactionsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TagsOnTransactions.
   * @param {TagsOnTransactionsUpsertArgs} args - Arguments to update or create a TagsOnTransactions.
   * @example
   * // Update or create a TagsOnTransactions
   * const tagsOnTransactions = await prisma.tagsOnTransactions.upsert({
   *   create: {
   *     // ... data to create a TagsOnTransactions
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TagsOnTransactions we want to update
   *   }
   * })
   */
  upsert<T extends TagsOnTransactionsUpsertArgs>(args: Prisma.SelectSubset<T, TagsOnTransactionsUpsertArgs<ExtArgs>>): Prisma.Prisma__TagsOnTransactionsClient<runtime.Types.Result.GetResult<Prisma.$TagsOnTransactionsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TagsOnTransactions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TagsOnTransactionsCountArgs} args - Arguments to filter TagsOnTransactions to count.
   * @example
   * // Count the number of TagsOnTransactions
   * const count = await prisma.tagsOnTransactions.count({
   *   where: {
   *     // ... the filter for the TagsOnTransactions we want to count
   *   }
   * })
  **/
  count<T extends TagsOnTransactionsCountArgs>(
    args?: Prisma.Subset<T, TagsOnTransactionsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TagsOnTransactionsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TagsOnTransactions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TagsOnTransactionsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TagsOnTransactionsAggregateArgs>(args: Prisma.Subset<T, TagsOnTransactionsAggregateArgs>): Prisma.PrismaPromise<GetTagsOnTransactionsAggregateType<T>>

  /**
   * Group by TagsOnTransactions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TagsOnTransactionsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TagsOnTransactionsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TagsOnTransactionsGroupByArgs['orderBy'] }
      : { orderBy?: TagsOnTransactionsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TagsOnTransactionsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTagsOnTransactionsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TagsOnTransactions model
 */
readonly fields: TagsOnTransactionsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TagsOnTransactions.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TagsOnTransactionsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  tag<T extends Prisma.TagsDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TagsDefaultArgs<ExtArgs>>): Prisma.Prisma__TagsClient<runtime.Types.Result.GetResult<Prisma.$TagsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  transaction<T extends Prisma.TransactionDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TransactionDefaultArgs<ExtArgs>>): Prisma.Prisma__TransactionClient<runtime.Types.Result.GetResult<Prisma.$TransactionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TagsOnTransactions model
 */
export interface TagsOnTransactionsFieldRefs {
  readonly tagId: Prisma.FieldRef<"TagsOnTransactions", 'String'>
  readonly transactionId: Prisma.FieldRef<"TagsOnTransactions", 'String'>
}
    

// Custom InputTypes
/**
 * TagsOnTransactions findUnique
 */
export type TagsOnTransactionsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TagsOnTransactions
   */
  select?: Prisma.TagsOnTransactionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TagsOnTransactions
   */
  omit?: Prisma.TagsOnTransactionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TagsOnTransactionsInclude<ExtArgs> | null
  /**
   * Filter, which TagsOnTransactions to fetch.
   */
  where: Prisma.TagsOnTransactionsWhereUniqueInput
}

/**
 * TagsOnTransactions findUniqueOrThrow
 */
export type TagsOnTransactionsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TagsOnTransactions
   */
  select?: Prisma.TagsOnTransactionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TagsOnTransactions
   */
  omit?: Prisma.TagsOnTransactionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TagsOnTransactionsInclude<ExtArgs> | null
  /**
   * Filter, which TagsOnTransactions to fetch.
   */
  where: Prisma.TagsOnTransactionsWhereUniqueInput
}

/**
 * TagsOnTransactions findFirst
 */
export type TagsOnTransactionsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TagsOnTransactions
   */
  select?: Prisma.TagsOnTransactionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TagsOnTransactions
   */
  omit?: Prisma.TagsOnTransactionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TagsOnTransactionsInclude<ExtArgs> | null
  /**
   * Filter, which TagsOnTransactions to fetch.
   */
  where?: Prisma.TagsOnTransactionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TagsOnTransactions to fetch.
   */
  orderBy?: Prisma.TagsOnTransactionsOrderByWithRelationInput | Prisma.TagsOnTransactionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TagsOnTransactions.
   */
  cursor?: Prisma.TagsOnTransactionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TagsOnTransactions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TagsOnTransactions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TagsOnTransactions.
   */
  distinct?: Prisma.TagsOnTransactionsScalarFieldEnum | Prisma.TagsOnTransactionsScalarFieldEnum[]
}

/**
 * TagsOnTransactions findFirstOrThrow
 */
export type TagsOnTransactionsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TagsOnTransactions
   */
  select?: Prisma.TagsOnTransactionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TagsOnTransactions
   */
  omit?: Prisma.TagsOnTransactionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TagsOnTransactionsInclude<ExtArgs> | null
  /**
   * Filter, which TagsOnTransactions to fetch.
   */
  where?: Prisma.TagsOnTransactionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TagsOnTransactions to fetch.
   */
  orderBy?: Prisma.TagsOnTransactionsOrderByWithRelationInput | Prisma.TagsOnTransactionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TagsOnTransactions.
   */
  cursor?: Prisma.TagsOnTransactionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TagsOnTransactions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TagsOnTransactions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TagsOnTransactions.
   */
  distinct?: Prisma.TagsOnTransactionsScalarFieldEnum | Prisma.TagsOnTransactionsScalarFieldEnum[]
}

/**
 * TagsOnTransactions findMany
 */
export type TagsOnTransactionsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TagsOnTransactions
   */
  select?: Prisma.TagsOnTransactionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TagsOnTransactions
   */
  omit?: Prisma.TagsOnTransactionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TagsOnTransactionsInclude<ExtArgs> | null
  /**
   * Filter, which TagsOnTransactions to fetch.
   */
  where?: Prisma.TagsOnTransactionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TagsOnTransactions to fetch.
   */
  orderBy?: Prisma.TagsOnTransactionsOrderByWithRelationInput | Prisma.TagsOnTransactionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TagsOnTransactions.
   */
  cursor?: Prisma.TagsOnTransactionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TagsOnTransactions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TagsOnTransactions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TagsOnTransactions.
   */
  distinct?: Prisma.TagsOnTransactionsScalarFieldEnum | Prisma.TagsOnTransactionsScalarFieldEnum[]
}

/**
 * TagsOnTransactions create
 */
export type TagsOnTransactionsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TagsOnTransactions
   */
  select?: Prisma.TagsOnTransactionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TagsOnTransactions
   */
  omit?: Prisma.TagsOnTransactionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TagsOnTransactionsInclude<ExtArgs> | null
  /**
   * The data needed to create a TagsOnTransactions.
   */
  data: Prisma.XOR<Prisma.TagsOnTransactionsCreateInput, Prisma.TagsOnTransactionsUncheckedCreateInput>
}

/**
 * TagsOnTransactions createMany
 */
export type TagsOnTransactionsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TagsOnTransactions.
   */
  data: Prisma.TagsOnTransactionsCreateManyInput | Prisma.TagsOnTransactionsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TagsOnTransactions createManyAndReturn
 */
export type TagsOnTransactionsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TagsOnTransactions
   */
  select?: Prisma.TagsOnTransactionsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TagsOnTransactions
   */
  omit?: Prisma.TagsOnTransactionsOmit<ExtArgs> | null
  /**
   * The data used to create many TagsOnTransactions.
   */
  data: Prisma.TagsOnTransactionsCreateManyInput | Prisma.TagsOnTransactionsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TagsOnTransactionsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * TagsOnTransactions update
 */
export type TagsOnTransactionsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TagsOnTransactions
   */
  select?: Prisma.TagsOnTransactionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TagsOnTransactions
   */
  omit?: Prisma.TagsOnTransactionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TagsOnTransactionsInclude<ExtArgs> | null
  /**
   * The data needed to update a TagsOnTransactions.
   */
  data: Prisma.XOR<Prisma.TagsOnTransactionsUpdateInput, Prisma.TagsOnTransactionsUncheckedUpdateInput>
  /**
   * Choose, which TagsOnTransactions to update.
   */
  where: Prisma.TagsOnTransactionsWhereUniqueInput
}

/**
 * TagsOnTransactions updateMany
 */
export type TagsOnTransactionsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TagsOnTransactions.
   */
  data: Prisma.XOR<Prisma.TagsOnTransactionsUpdateManyMutationInput, Prisma.TagsOnTransactionsUncheckedUpdateManyInput>
  /**
   * Filter which TagsOnTransactions to update
   */
  where?: Prisma.TagsOnTransactionsWhereInput
  /**
   * Limit how many TagsOnTransactions to update.
   */
  limit?: number
}

/**
 * TagsOnTransactions updateManyAndReturn
 */
export type TagsOnTransactionsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TagsOnTransactions
   */
  select?: Prisma.TagsOnTransactionsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TagsOnTransactions
   */
  omit?: Prisma.TagsOnTransactionsOmit<ExtArgs> | null
  /**
   * The data used to update TagsOnTransactions.
   */
  data: Prisma.XOR<Prisma.TagsOnTransactionsUpdateManyMutationInput, Prisma.TagsOnTransactionsUncheckedUpdateManyInput>
  /**
   * Filter which TagsOnTransactions to update
   */
  where?: Prisma.TagsOnTransactionsWhereInput
  /**
   * Limit how many TagsOnTransactions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TagsOnTransactionsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * TagsOnTransactions upsert
 */
export type TagsOnTransactionsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TagsOnTransactions
   */
  select?: Prisma.TagsOnTransactionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TagsOnTransactions
   */
  omit?: Prisma.TagsOnTransactionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TagsOnTransactionsInclude<ExtArgs> | null
  /**
   * The filter to search for the TagsOnTransactions to update in case it exists.
   */
  where: Prisma.TagsOnTransactionsWhereUniqueInput
  /**
   * In case the TagsOnTransactions found by the `where` argument doesn't exist, create a new TagsOnTransactions with this data.
   */
  create: Prisma.XOR<Prisma.TagsOnTransactionsCreateInput, Prisma.TagsOnTransactionsUncheckedCreateInput>
  /**
   * In case the TagsOnTransactions was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TagsOnTransactionsUpdateInput, Prisma.TagsOnTransactionsUncheckedUpdateInput>
}

/**
 * TagsOnTransactions delete
 */
export type TagsOnTransactionsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TagsOnTransactions
   */
  select?: Prisma.TagsOnTransactionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TagsOnTransactions
   */
  omit?: Prisma.TagsOnTransactionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TagsOnTransactionsInclude<ExtArgs> | null
  /**
   * Filter which TagsOnTransactions to delete.
   */
  where: Prisma.TagsOnTransactionsWhereUniqueInput
}

/**
 * TagsOnTransactions deleteMany
 */
export type TagsOnTransactionsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TagsOnTransactions to delete
   */
  where?: Prisma.TagsOnTransactionsWhereInput
  /**
   * Limit how many TagsOnTransactions to delete.
   */
  limit?: number
}

/**
 * TagsOnTransactions without action
 */
export type TagsOnTransactionsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TagsOnTransactions
   */
  select?: Prisma.TagsOnTransactionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TagsOnTransactions
   */
  omit?: Prisma.TagsOnTransactionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TagsOnTransactionsInclude<ExtArgs> | null
}
